### PR TITLE
deps: upgrade koa-static-cache to 4.x

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by atian25** [comment]
大版本主要改啥了？

发自我的 iPhone

**Comment by fengmk2** [comment]
prefix check 性能提升

**Comment by dead-horse** [comment]
@atian25 主要的 breaking change 是 prefix 不能用中文，对我们没有影响

**Comment by fengmk2** [comment]
我发个版本

**Comment by fengmk2** [comment]
1.2.0

**Comment by fengmk2** [comment]
## before

- hello world: 8909
- view: 6131

## after

- hello world: 9001
- view: 6015

**Pull request merged**
