### PR TITLE
feat: add range support

### PR DESCRIPTION
**Pull request by helloyou2012**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

None

##### Description of change

Add range support and fix https://github.com/koajs/static-cache/issues/1

### CODE REVIEW

**Comment by helloyou2012** [comment]
A question about this bug: https://cnodejs.org/topic/5a531ac2afa0a121784a8a48

**Comment by dead-horse** [comment]
please add a test case for this feature.

**Comment by helloyou2012** [comment]
@dead-horse test case is added, plz check.

**Comment by dead-horse** [comment]
2.1.0

**Comment by dead-horse** [comment]
https://github.com/koajs/koa-range/issues/12 暂时还不能 pick 到 egg@1

**Comment by dead-horse** [comment]
已 pick 回 egg-static@1.5.0

**Pull request merged**
